# Generated by Django 5.1.7 on 2025-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('local', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Culto', 'CULTO'), ('Aniversario', 'ANIVERSARIO'), ('Churrasco', 'CHURRASCO')], max_length=255)),
            ],
        ),
    ]
